field: 93ccdeb5-5e68-4d61-b506-42ad05963b18 # FAQ Section
fieldLayouts:
  cce136ff-e2ad-4716-9484-cdc1fec3849f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf2a1d13-2b1d-40a4-a2cc-11fcf1b7a64d # FAQ Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6003156-4783-4e0f-a355-c9f8a8ed3952
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6441d6aa-822b-441d-9848-4e1d4012b32d # FAQ Descriptions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbda2ac9-979a-45a4-ac5b-5f7fbb855325
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 754ef6d3-a72f-4e94-a3d7-18d69aeb71e0
        userCondition: null
fields:
  6441d6aa-822b-441d-9848-4e1d4012b32d: # FAQ Descriptions
    columnSuffix: lwwwgbzf
    contentColumnType: text
    fieldGroup: null
    handle: faqDescriptions
    instructions: null
    name: 'FAQ Descriptions'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bf2a1d13-2b1d-40a4-a2cc-11fcf1b7a64d: # FAQ Title
    columnSuffix: ofakeeqq
    contentColumnType: text
    fieldGroup: null
    handle: faqTitle
    instructions: null
    name: 'FAQ Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faqSection
name: 'FAQ Section'
sortOrder: 1
