field: 857adbe8-e650-4e97-a7f8-4e4c248d7ba4 # Video Link
fieldLayouts:
  5ecacf93-c594-4077-9832-5b9f3d343faa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7df5c12c-123e-4f71-b3aa-777a042593b2 # Video Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4de22439-48b9-4d17-8858-36ed92c16425
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98b35a41-caca-4ad4-99a6-1ef71b8b3443
        userCondition: null
fields:
  7df5c12c-123e-4f71-b3aa-777a042593b2: # Video Link URL
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoLinkUrl
    instructions: null
    name: 'Video Link URL'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: videoLink
name: 'Video Link'
sortOrder: 1
