defaultPlacement: end
fieldLayouts:
  50c5f4b7-1c6d-4ad8-b5c2-9240385291e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8cfef236-42f4-479c-9fb9-3fc768df2c9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b41acddc-f62e-46cf-a879-f0a4046957b9 # Product Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a759780-fccd-4f61-bc2d-e327dd22a640
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1df72a7-d46b-42d4-a01b-76072261fcf8 # Show Home Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09ba42b3-7c7c-42b4-bbd4-fc01e4047919
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 06685d84-706b-4704-9f08-77d897cc909a # Featured Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a26ed09-dd19-4e4e-83ce-914469e9ba63
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 3710f7f6-6558-4a4c-9408-221d33c6c41b
        userCondition: null
handle: productCategory
name: 'Product Category'
siteSettings:
  5e61c7f8-a4a4-4d6f-b4e9-1e5a8beb0df4: # Aag India
    hasUrls: true
    template: category/_sub-categories
    uriFormat: 'category/{slug}'
structure:
  maxLevels: null
  uid: f5d1b985-659e-4fd5-848c-7a1a3809c5b0
