childBlocks: null
conditions: null
description: ''
enabled: true
field: df14da86-5f3f-4599-bf52-433bff7e01fc # Page Modules
fieldLayouts:
  c64ab980-0c56-46a2-823a-0a0425e39989:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa2b25e0-321e-4c38-8854-27cb7164898d # Full Text Editor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 858ae686-2032-4c73-b3fa-64c3b054356d
            userCondition: null
            warning: null
            width: 100
        name: 'Full Text Editor'
        uid: f6f02c60-31cd-422a-a18b-ac3003d56b42
        userCondition: null
group: null
groupChildBlockTypes: true
handle: fullTextEditorModule
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Full Text Editor'
sortOrder: 2
topLevel: true
