childBlocks: null
conditions: null
description: ''
enabled: true
field: df14da86-5f3f-4599-bf52-433bff7e01fc # Page Modules
fieldLayouts:
  a11308e2-d169-434e-b677-50b1434dd669:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec35da0d-65ea-487b-b789-ce38d80555d3 # About Us Img Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f731406-9ec4-4b7f-b7b8-a4df3efb32f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a734bd9-9bb7-4765-8153-41ac14a15cef # About Us Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e089d899-436a-4647-b524-0a6d8001101f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c9d0a10-cfe2-4edd-b4fd-f3f784354459 # About Us Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f1a2ff2-5e99-4327-9f1f-70c4706d37d9
            userCondition: null
            warning: null
            width: 100
        name: 'Img with Descriptions'
        uid: 4f54fdc0-2c6f-481f-9df2-d1538d3d0b06
        userCondition: null
group: null
groupChildBlockTypes: true
handle: imgWithDescriptions
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Img with Descriptions'
sortOrder: 1
topLevel: true
