childBlocks: null
conditions: null
description: ''
enabled: true
field: df14da86-5f3f-4599-bf52-433bff7e01fc # Page Modules
fieldLayouts:
  e6d56003-fdd5-4f03-9995-acc009481b51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 268ca421-c885-4647-8172-854667af510d # PDF Download Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b9e1e5-d9d5-4870-b852-cd6a54b49d5e
            userCondition: null
            warning: null
            width: 100
        name: 'PDF Link'
        uid: 1112e190-f120-4ae6-94f8-8d88465cc6d5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: pdfdownloadlink
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: pdfDownloadLink
sortOrder: 6
topLevel: true
