childBlocks: null
conditions: null
description: ''
enabled: true
field: 685be52c-2adf-44c9-a43d-9d0f6491b4c0 # Product Detail
fieldLayouts:
  5b6fb46c-78b8-4e6e-9797-3232ea7c1355:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa2b25e0-321e-4c38-8854-27cb7164898d # Full Text Editor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 824bc334-ff80-48c4-a138-64ea82b8229d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ea23dd7-fd97-4ff4-bd74-714a4343232c # Product Detail Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9739c1a1-6969-45d8-87e5-f92623ee7826
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16dcbd0b-9b48-4062-a3ea-20875b152300 # Download Multiple PDF
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a2e416d-f485-4b51-8fdd-b3a7bab5dae7
            userCondition: null
            warning: null
            width: 100
        name: 'Product Detail'
        uid: 02e3c760-4b6a-4465-97f5-58d78b0d69dc
        userCondition: null
group: null
groupChildBlockTypes: true
handle: productDetail
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Product Detail'
sortOrder: 1
topLevel: true
