columnSuffix: jtwwrnin
contentColumnType: text
fieldGroup: 4467e6dc-f3ec-4e77-940a-71553d3dd0a4 # Page Module
handle: bannerTitle
instructions: null
name: 'Banner Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
