defaultPlacement: end
enableVersioning: true
handle: generalPage
name: 'General Page'
propagationMethod: all
siteSettings:
  5e61c7f8-a4a4-4d6f-b4e9-1e5a8beb0df4: # Aag India
    enabledByDefault: true
    hasUrls: true
    template: general-page/_entry
    uriFormat: '{slug}'
type: channel
