defaultPlacement: end
enableVersioning: true
handle: productDetail
name: 'Product Detail'
propagationMethod: all
siteSettings:
  5e61c7f8-a4a4-4d6f-b4e9-1e5a8beb0df4: # Aag India
    enabledByDefault: true
    hasUrls: true
    template: product-detail/_entry
    uriFormat: 'product-detail/{slug}'
type: channel
